[DEFAULTS]

# Whatever the default is here

[TNM]

path.aaf = ""
path.excel = ""
path.reaper = ""

excel.none = ""
excel.filename = ['DLG ID']
excel.line_text = ['English (United States)']
excel.character = ['Voice']
excel.select = ['Rec. Selection']
excel.takes = ['Rec. Takes']
excel.updated_line = ['Rec. Text Change']
excel.record_date = ['Date Recorded']

excel.hidden = []

aaf.mode = "Pulled Down Selects"
aaf.identifiers = [
    "4060",
    "4061",
    "416",
    "selects",
    "alts"
]

[WWE]

#WWE Config Here